### ISSUE TITLE
gitea database locked and does not load repositorys

### ISSUE THREAD

**Issue by braunbearded** [cider-security-research/cicd-goat#54]
Hi,

it seems like gitea is not loading properly because the database is locked for some reason.

I have no cpu or ram restriction in place so I can rule out any race condition based on performance issues. After a while the webserver for gitea starts but without any users and repos obviously.

Everything else works as expected. Do you have any idea why this might happened?

```bash
docker-compose logs gitea
...
gitea  | 2023/03/31 19:50:24 routers/init.go:131:GlobalInitInstalled() [I] SQLite3 support is enabled
gitea  | 2023/03/31 19:50:24 routers/common/db.go:20:InitDBEngine() [I] Beginning ORM engine initialization.
gitea  | 2023/03/31 19:50:24 routers/common/db.go:27:InitDBEngine() [I] ORM engine initialization attempt #1/10...
gitea  | 2023/03/31 19:50:24 cmd/web.go:153:runWeb() [I] PING DATABASE sqlite3
gitea  | 2023/03/31 19:50:38 main.go:117:main() [F] Failed to run app with [/usr/local/bin/gitea admin user create --username red_queen --password ciderland5# --email queen@localhost --admin]: CreateUser: database is locked
gitea  | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:3000
gitea  | Traceback (most recent call last):
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
gitea  |     conn = connection.create_connection(
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
gitea  |     raise err
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
gitea  |     sock.connect(sa)
gitea  | ConnectionRefusedError: [Errno 111] Connection refused
gitea  |
gitea  | During handling of the above exception, another exception occurred:
gitea  |
gitea  | Traceback (most recent call last):
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
gitea  |     httplib_response = self._make_request(
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
gitea  |     conn.request(method, url, **httplib_request_kw)
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
gitea  |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
gitea  |   File "/usr/lib/python3.8/http/client.py", line 1256, in request
gitea  |     self._send_request(method, url, body, headers, encode_chunked)
gitea  |   File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
gitea  |     self.endheaders(body, encode_chunked=encode_chunked)
gitea  |   File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
gitea  |     self._send_output(message_body, encode_chunked=encode_chunked)
gitea  |   File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
gitea  |     self.send(msg)
gitea  |   File "/usr/lib/python3.8/http/client.py", line 951, in send
gitea  |     self.connect()
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
gitea  |     conn = self._new_conn()
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
gitea  |     raise NewConnectionError(
gitea  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4568915af0>: Failed to establish a new connection: [Errno 111] Connection refused
gitea  |
gitea  | During handling of the above exception, another exception occurred:
gitea  |
gitea  | Traceback (most recent call last):
gitea  |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
gitea  |     resp = conn.urlopen(
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
gitea  |     retries = retries.increment(
gitea  |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
gitea  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
gitea  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/v1/users/red_queen/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4568915af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
gitea  |
gitea  | During handling of the above exception, another exception occurred:
gitea  |
gitea  | Traceback (most recent call last):
gitea  |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
gitea  |     return _run_code(code, main_globals, None,
gitea  |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
gitea  |     exec(code, run_globals)
gitea  |   File "/setup/giteacasc/__main__.py", line 4, in <module>
gitea  |     giteacasc()
gitea  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
gitea  |     return self.main(*args, **kwargs)
gitea  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1055, in main
gitea  |     rv = self.invoke(ctx)
gitea  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
gitea  |     return ctx.invoke(self.callback, **ctx.params)
gitea  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 760, in invoke
gitea  |     return __callback(*args, **kwargs)
gitea  |   File "/setup/giteacasc/__init__.py", line 23, in giteacasc
gitea  |     g = Gitea(admin_username, admin_password)
gitea  |   File "/setup/giteacasc/gitea.py", line 20, in __init__
gitea  |     res = requests.post(f'{self.API_BASE_URL}/users/{username}/tokens',
gitea  |   File "/usr/lib/python3.8/site-packages/requests/api.py", line 117, in post
gitea  |     return request('post', url, data=data, json=json, **kwargs)
gitea  |   File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
gitea  |     return session.request(method=method, url=url, **kwargs)
gitea  |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
gitea  |     resp = self.send(prep, **send_kwargs)
gitea  |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
gitea  |     r = adapter.send(request, **kwargs)
gitea  |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
gitea  |     raise ConnectionError(e, request=request)
gitea  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/v1/users/red_queen/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4568915af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
gitea  | /usr/bin/entrypoint	(wd: /)
gitea  | 2023/03/31 19:52:51 routers/init.go:137:GlobalInitInstalled() [I] ORM engine initialization successful!
gitea  | 2023/03/31 19:52:54 ...xer/stats/indexer.go:39:populateRepoIndexer() [I] Populating the repo stats indexer with existing repositories
gitea  | 2023/03/31 19:52:54 ...er/issues/indexer.go:144:func2() [I] PID 17: Initializing Issue Indexer: bleve
gitea  | 2023/03/31 19:52:55 ...er/issues/indexer.go:223:func3() [I] Issue Indexer Initialization took 602.900149ms
gitea  | 2023/03/31 19:52:55 routers/init.go:86:syncAppPathForGit() [I] AppPath changed from '' to '/usr/local/bin/gitea'
gitea  | 2023/03/31 19:52:55 routers/init.go:88:syncAppPathForGit() [I] re-sync repository hooks ...
gitea  | 2023/03/31 19:52:55 routers/init.go:91:syncAppPathForGit() [I] re-write ssh public keys ...
gitea  | 2023/03/31 19:52:56 cmd/web.go:208:listen() [I] Listen: http://0.0.0.0:3000
gitea  | 2023/03/31 19:52:56 cmd/web.go:212:listen() [I] AppURL(ROOT_URL): http://localhost:3000/
gitea  | 2023/03/31 19:52:56 cmd/web.go:215:listen() [I] LFS server enabled
gitea  | 2023/03/31 19:52:56 ...s/graceful/server.go:61:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 17
gitea  | 2023/03/31 19:54:01 Started GET /api/v1/repos/Wonderland/caterpillar for 172.22.0.5:50470
gitea  | 2023/03/31 19:54:01 Completed GET /api/v1/repos/Wonderland/caterpillar 404 Not Found in 2.546312ms
gitea  | 2023/03/31 19:54:01 Started GET /api/v1/repos/Wonderland/mad-hatter for 172.22.0.5:50472
gitea  | 2023/03/31 19:54:01 Completed GET /api/v1/repos/Wonderland/mad-hatter 404 Not Found in 1.090362ms
gitea  | 2023/03/31 19:54:01 Started GET /api/v1/repos/Wonderland/dormouse for 172.22.0.5:50486
gitea  | 2023/03/31 19:54:01 Completed GET /api/v1/repos/Wonderland/dormouse 404 Not Found in 889.327µs
gitea  | 2023/03/31 19:54:01 Started GET /api/v1/repos/Wonderland/caterpillar for 172.22.0.5:50490
gitea  | 2023/03/31 19:54:01 Completed GET /api/v1/repos/Wonderland/caterpillar 404 Not Found in 2.295161ms
```

```bash
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.17.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.51GiB
 Name: <redacted>
 ID: <redacted>
 Docker Root Dir: /mnt/hdd_linux/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by asi-cider** [comment]
Hey @braunbearded , thanks for reporting this issue!
Which OS is your computer running?
Try to replace line 6 in gitea/run.sh to:
`while true
do
  gitea_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:3000/ )
  if [ "$gitea_status_code" -eq 200 ]; then
    break
  fi
  sleep 5
done`
and rebuild the container. Please update if it helps.
If there are lines missing from the beginning of the log can you please post them here?

**Comment by braunbearded** [comment]
Hey @asi-cider, this seems to fix the issue. 

I'm running an update version of arch so nothing special. I however did move my /var/lib/docker folder to an different partition on an hdd. Maybe the slow read/write speed of the hdd cause the issue.

Are you planning on pushing this fix? Then I would recommend make it a bit more verbose like this:

```bash
while true
do
  gitea_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:3000/ )
  if [ "$gitea_status_code" -eq 200 ]; then
    echo "Gitea ready. Continue with setup..."
    break
  fi
  echo "Gitea is not ready. Waiting 5 seconds..."
  sleep 5
done
```

Anyway feel free to close the issue or contact me if I should do some tests (again).
